### PR TITLE
Use audbcards package

### PR DESCRIPTION
**Pull request by hagenw**
This uses the new `audbcards` Python package for creating the data cards.

### CODE REVIEW

**Comment by hagenw** [comment]
Cool, now it is able to install the package and fails with the same message as I got locally:

image

**Comment by hagenw** [comment]
The name of the stored dataset file should be changed from `emodb_from_template.rst` to `emodb.rst`.

**Comment by ChristianGeng** [comment]
> The name of the stored dataset file should be changed from `emodb_from_template.rst` to `emodb.rst`.

Done. For me this is working now.

**Comment by hagenw** [comment]
Cool,  I restarted the pipeline and it is now building.
I also tested it locally and it produces the following:

image

**Pull request merged**
